<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Fonts\Inter-VariableFont_slnt,wght.ttf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LilyPadTest\LilyPadTest.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Fonts\Inter-VariableFont_slnt,wght.ttf" />
  </ItemGroup>

</Project>
